CHOICE_MESSAGE = "Choose a sentence number. "
NOT_A_NUMBER_ERROR = "Please choose a valid number."
SENTENCE_FILE = "grade2sentences.txt"
VOCABULARY_FILE = "grade2vocab.txt"
WELCOME_MESSAGE = "Simple Sentence Generator. Press enter..."
